pipeline {
  agent any
  stages {
    stage('Test') {
      steps {
        script {
          docker.image('node:16-alpine').run('--name my_container --rm=false -d')
          sh 'docker ps -a'
        }
      }
    }
  }
}
